name: bella-bona-bot
services:
  - name: api
    source_dir: /
    github:
      repo: YOUR_GITHUB_USERNAME/bella-bona-bot
      branch: main
    run_command: npm start
    build_command: npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: BELLA_BONA_USERNAME
        scope: RUN_AND_BUILD_TIME
        value: ${BELLA_BONA_USERNAME}
      - key: BELLA_BONA_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: ${BELLA_BONA_PASSWORD}
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "8080"
